version: 2.1
orbs:
  slim-harden-orb: slimdevops/test-harden-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - slim-harden-orb/instrumentation:
          name: Instrumentation
          sourceImage: sreejithfocaloid/node-example
        - run:
            name: Run Container
            command: |
              chmod +x ../scripts/run.sh
              ../scripts/run.sh
        - run:
            name: Stop Container
            command: |
              chmod +x ../scripts/cleanup.sh
              ../scripts/cleanup.sh    
      - slim-harden-orb/hardening:
          name: Hardening
          requires:
            - Instrumentation
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: slimdevops/test-harden-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - Instrumentation
            - Hardening
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
