version: 2.1
orbs:
  slim-harden-orb: slimdevops/test-harden-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  run-instrumented-container:
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: cimg/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Run Container
          command: |
            chmod +x ./src/scripts/run.sh
            ./src/scripts/run.sh
      - run:
          name: Stop Container
          command: |
            chmod +x ./src/scripts/cleanup.sh
            ./src/scripts/cleanup.sh

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - slim-harden-orb/instrumentation:
          name: Instrumentation
          sourceImage: sreejithfocaloid/node-example
      - run-instrumented-container:
          name: Run Instrumented
          requires:
            - Instrumentation    
      - slim-harden-orb/hardening:
          name: Hardening
          requires:
            - Run Instrumented
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: slimdevops/test-harden-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - Instrumentation
            - Hardening
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
